---@module 'custom.icons'
---@author 'Roger Steve Ruiz'
---@license 'MIT'

-- Encuentren más iconos aquí: (https://www.nerdfonts.com/cheat-sheet)
return {
    kind = {
        Class = "",
        Color = "",
        Constant = "",
        Constructor = "",
        Enum = "",
        EnumMember = "",
        Event = "",
        Field = "",
        File = "",
        Flag = "󰈻",
        Folder = "",
        Function = "󰊕",
        Interface = "",
        Key = "",
        Method = "m",
        Module = "",
        Namespace = "",
        Operator = "",
        Package = " ",
        Property = "",
        Reference = "",
        Snippet = "",
        Struct = "",
        Text = "󰊄",
        TypeParameter = "",
        Unit = "",
        Value = "󱢏",
        Variable = "",
    },
    type = {
        Array = "",
        Boolean = "",
        Float = "󱂡",
        Null = "󰟢",
        Number = "",
        Object = "󰅩",
        String = "",
    },
    documents = {
        File = "",
        Files = "",
        Folder = "",
        OpenFolder = "",
    },
    git = {
        Add = "",
        Mod = "",
        Remove = "",
        Ignore = "",
        Rename = "",
        Diff = "",
        Repo = "",
        Untracked = "",
        ui = {
            add = "│",
            change = "│",
            delete = "┘",
            topdelete = "┐",
            changedelete = "├",
            untracked = "┤",
        },
    },
    ui = {
        Lock = "",
        Circle = "",
        BigCircle = "",
        BigUnfilledCircle = "",
        Close = "",
        NewFile = "",
        Search = "",
        Lightbulb = "󰌵",
        Project = "",
        Dashboard = "",
        History = "",
        Comment = "",
        Bug = "",
        Code = "",
        Telescope = "",
        Gear = "",
        Package = "",
        List = "",
        SignIn = "",
        Check = "",
        Fire = "󰈸",
        Note = "󰎚",
        BookMark = "",
        Pencil = "",
        ChevronRight = "",
        ChevronLeft = "",
        Table = "",
        Time = "",
        Calendar = "󰃭",
        CalendarTime = "󰃰",
        SelectionCaret = " ",
        HorizontalDots = "󰇘",
        PowerlineRightFill = "",
        PowerlineLeftFill = "",
        PowerlineRightEmpty = "",
        PowerlineLeftEmpty = "",
        LineNumber = "",
        ColumnNumber = "",
        SeparatorForward = "",
        SeparatorBackward = "",
        InnerNode = "├○",
        OuterNode = "╰○",
    },
    diagnostics = {
        Sev1 = "󰈸",
        Sev2 = "",
        Sev3 = "",
        Description = "󰅌",
        VirtualText = "󰆈",
        File = "󰩋",
        Head = "󱌽",
        Error = "",
        Warning = "",
        Information = "",
        Question = "",
        Hint = "",
        Todo = "",
        Perf = "󱐋",
        Test = "󰙨",
        Hack = "󰗹",
    },
    misc = {
        Robot = "󰚩",
        Squirrel = "",
        Tag = "",
        Watch = "",
        Tree = "",
    },
}
