#!/bin/sh

# Definimos a `animado` afuera de la comprueba abajo para que todas las
# capturas son quieto.
animado=""

# NOTE: Requiere `coreutils` instalado entonces vamos a comprobar
if type shuf > /dev/null 2>&1
then
  if test "$(shuf -i 1-10 -n 1)" -gt 5
  then
    animado="--animate 3"
  fi
fi

if [ -z "${LOLCOMMITS_CAPTURE_DISABLED}" ]
then
  # PERF: Usando el `system_profiler` de macOS y no la instrucción `lolcommits
  # --devices` porque es mui despacio. Con el `system_profiler` ahoro casi 2.8
  # segundos para saber si mi camera de 1080p esta conectado o no.
  LOLCOMMITS_DEVICE=$(
    system_profiler \
      SPCameraDataType \
      -json \
      -detailLevel basic \
    | jq -r '.SPCameraDataType[0]."_name" | select(. == "HD Pro Webcam C920")'
  )
  if [ -z "${LOLCOMMITS_DEVICE}" ]
  then
    unset LOLCOMMITS_DEVICE
  else
    export LOLCOMMITS_DEVICE
  fi
  LANG="" && \
  PATH="$PATH:/Users/rsr/.rvm/rubies/ruby-3.0.1/bin" && \
  if [ ! -d "${GIT_DIR}/rebase-merge" ] && \
     [ "${LOLCOMMITS_CAPTURE_DISABLED}" != "true" ]
  then
    # shellcheck disable=SC2086
    lolcommits \
      --capture \
      --stealth \
      --delay 2 \
      --fork \
      ${animado-}
  fi
fi

# NOTE: Esto muestra el color que corresponde a la última confirmación
if [ -x "$(which commit-colors)" ]
then
  commit-colors "$(git rev-parse HEAD)"
fi
