# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "$all$directory$character"

[character]
success_symbol = "[    ](bold green)"
error_symbol = "[    ](bold red)"
vimcmd_symbol = "[    ](bold purple)"
format = "$symbol "

[cmd_duration]
min_time = 5_000
format = "[  $duration](bold yellow)"

[ruby]
symbol = " "
format = "[$symbol](bright-red)[$version ](dimmed bright-red)"

[nodejs]
symbol = " "
format = "[$symbol](bright-green)[$version ](dimmed bright-green)"

[golang]
symbol = "ﳑ "
format = "[$symbol](bright-cyan)[$version ](dimmed bright-cyan)"

[directory]
truncation_symbol = "  "
