# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """$all\
$package\
[ﲾ ](bold yellow) $rust$nodejs$golang$terraform$ruby
$cmd_duration$character"""

[character]
success_symbol = "[    ](bold green)"
error_symbol = "[    ](bold red)"
vimcmd_symbol = "[    ](bold purple)"
format = "$symbol "

[cmd_duration]
min_time = 5_000
format = "[  $duration](bold yellow) "

[ruby]
symbol = " "
format = "[$symbol](bright-red)[$version ](dimmed bright-red)"

[nodejs]
symbol = " "
format = "[$symbol](bright-green)[$version ](dimmed bright-green)"

[golang]
symbol = "ﳑ "
format = "[$symbol](bright-cyan)[$version ](dimmed bright-cyan)"

[rust]
symbol = " "
format = "[$symbol](bright-red)[$version ](dimmed bright-red)"

[terraform]
symbol = " "
detect_files = [".terraform-version"]
format = "[$symbol](bright-cyan) [$version ](dimmed bright-cyan)"

[package]
symbol = "  "
display_private = true
format = "[$symbol$version]($style) "

[git_branch]
symbol = " "
format = "[$symbol](bold green)[$branch(:$remote_branch)](bold #A393BF) "

[git_status]
format = "([](bold #F17300) [$all_status$ahead_behind]($style))"
modified = "[ﱐ](bold cyan) "
staged = "[](bold cyan) "
deleted = "[](bold red) "
untracked = "[](bold yellow) "
ahead = "[](bold cyan) "
behind = "[](bold cyan) "
conflicted = "[](bold yellow) "
stashed = "[﬒](bold magenta) "

[directory]
truncation_symbol = " "
home_symbol = "~"
style = "bold #A393BF dimmed"
repo_root_format = "[$before_root_path]($style)[ $repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
format = "[ ](bold cyan) [$path]($style)[$read_only]($read_only_style) "
