# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """$directory$git_branch$git_commit${custom.git_color}$git_state$git_metrics$git_status$time
$aws\
$package\
[ﲾ ](bold yellow) $rust$nodejs$golang$terraform$ruby$nix_shell
$jobs$cmd_duration$character"""

[character]
success_symbol = "[    ](bold green)"
error_symbol = "[    ](bold red)"
vimcmd_symbol = "[    ](bold purple)"
format = "$symbol "

[cmd_duration]
min_time = 5_000
format = "[  $duration](bold yellow) "

[ruby]
symbol = " "
format = "[$symbol](bright-red)[$version ](bold dimmed bright-red)"

[nodejs]
symbol = " "
format = "[$symbol](bright-green)[$version ](bold dimmed bright-green)"

[golang]
symbol = "ﳑ "
format = "[$symbol](bright-cyan)[$version ](bold dimmed bright-cyan)"

[rust]
symbol = " "
format = "[$symbol](bright-red)[$version ](bold dimmed bright-red)"

[terraform]
symbol = " "
detect_files = [".terraform-version"]
format = "[$symbol](bright-cyan) [$version ](bold dimmed bright-cyan)"

[aws]
symbol = "  "
expiration_symbol = ""
format = '[ ](bold bright-white) [$symbol](bold #ff9900)[($profile )(\($region\) )($duration )]($style) '

[aws.region_aliases]
us-gov-west-1 = "  us-gov-west-1"
us-gov-east-1 = "  us-gov-east-1"

[aws.profile_aliases]
transcom-gov-milmove-demo = "  蠟"
transcom-gov-milmove-exp = "   "
transcom-gov-milmove-loadtest = "   "
transcom-gov-milmove-stg = "撚   "
transcom-gov-milmove-prd = "撚 嘆"
transcom-gov-org-root = "   "

[package]
symbol = " "
display_private = true
format = "[$symbol]($style)[$version]($style dimmed) "

[git_branch]
symbol = " "
format = "[$symbol](bold green)[$branch(:$remote_branch)](bold #A393BF) "

[git_status]
format = "([](bold #F04E33) [$all_status$ahead_behind]($style) )"
modified = "[ﱐ](bold cyan) "
staged = "[](bold cyan) "
deleted = "[](bold red) "
untracked = "[](bold yellow) "
ahead = "[](bold cyan) "
behind = "[](bold cyan) "
conflicted = "[](bold yellow) "
stashed = "[﬒](bold magenta) "

[git_metrics]
format = "([ $added]($added_style) )([ $deleted]($deleted_style) )"
disabled = false

[git_commit]
commit_hash_length = 7
only_detached = false
format = '[\($hash$tag\)](bold #A393BF dimmed) '

[directory]
truncation_length = 5
truncation_symbol = " "
home_symbol = "~"
style = "bold #7FDEFF"
repo_root_style = "bold #F04E33"
truncate_to_repo = true
format = "[  $path]($style)[$read_only]($read_only_style) "
repo_root_format = "[  ]($style)[$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

# [directory.substitutions]
# "~/Developer/transcom/mymove" = "transcom/mymove"

[jobs]
symbol = " "
style = "bold purple"

[time]
disabled = false
time_format = "%T"
format = "[﨟](#815355)[$time](bold #c3b299 dimmed) "
utc_time_offset = "local"

# [custom.git_spark]
# command = "current_git_activity"
# symbol = " "
# style = "white bold dimmed"
# format = "[$symbol](bold #F04E33)[($output )]($style)"
# detect_folders = [".git"]                              # filters git directories

[custom.git_color]
command = 'current_git_color'
symbol = ""
detect_folders = ['.git']
